import {useEffect, useState} from 'react';

const serena='./src/file_000000003f60820eb8adacc5bed5ae6c.png';

type Question={prompt:string; options:string[]; answer:number};
type Story={title:string; category:string; icon:string; text:string; questions?:Question[]};

const stories:Story[]=[
  {title:'La carta bajo la lluvia',category:'Amor',icon:'♡',text:'Serena encontró una carta doblada bajo el banco del patio justo cuando empezó a llover. No tenía nombre, solo una frase: “Tu risa ilumina los días difíciles”. Durante toda la clase pensó que quizá era para ella. Al salir, vio a Mateo buscando algo entre los charcos. Serena le devolvió la carta y él, muy colorado, confesó que aún no se atrevía a entregársela. Caminaron juntos bajo el paraguas. No hicieron grandes promesas; compartieron una sonrisa tímida y la certeza de que algo bonito acababa de comenzar.'},
  {title:'El examen imposible',category:'Escuela',icon:'✦',text:'El lunes, Serena descubrió que el examen de historia era mucho más difícil de lo esperado. Por un instante quiso rendirse, pero recordó las tardes estudiando con Ami. Respiró profundo y respondió primero las preguntas que conocía. Después regresó a las complicadas y encontró pistas entre sus propios apuntes mentales. Al terminar, no sabía si obtendría la mejor nota, aunque se sentía orgullosa. Esa tarde comprendió que ser valiente no significa saberlo todo, sino confiar en el esfuerzo realizado y seguir adelante cuando aparecen las dudas.'},
  {title:'Domingo de panqueques',category:'Familia',icon:'☾',text:'El domingo, Serena despertó con olor a panqueques y encontró a su hermano intentando preparar el desayuno. La cocina parecía un campo de batalla: harina en el suelo, leche sobre la mesa y una montaña de platos. En vez de burlarse, se puso un delantal y decidió ayudarlo. Su madre llegó justo cuando ambos servían el panqueque más torcido del mundo. Los tres rieron tanto que casi olvidaron comer. Serena guardó aquel momento en su corazón, porque entendió que los recuerdos perfectos suelen nacer de planes completamente imperfectos.'},
  {title:'Luna no vuelve a casa',category:'Mascotas',icon:'♧',text:'Luna no regresó a la hora de cenar y Serena recorrió el vecindario llamándola con el corazón acelerado. Preguntó en la tienda, miró bajo los autos y pegó pequeños avisos en los postes. Cuando ya anochecía, escuchó un maullido cerca de la biblioteca. Luna estaba en una rama, asustada pero ilesa. Serena pidió ayuda para bajarla y la abrazó con fuerza. De regreso en casa, prometió revisar siempre la ventana. Aquella noche, Luna durmió a sus pies y Serena agradeció en silencio tener nuevamente cerca a su pequeña compañera.'},
  {title:'Un baile inesperado',category:'Romance',icon:'♬',text:'Serena pensaba quedarse en casa la noche del baile escolar porque no tenía pareja. Minako apareció con un vestido prestado y una idea sencilla: irían juntas a divertirse. En el gimnasio, las luces parecían estrellas y la música borró pronto la vergüenza. Cerca del final, Darien le ofreció la mano y preguntó si quería bailar. Serena tropezó en el primer paso, pero él sonrió y continuaron. Descubrió que el momento romántico que había imaginado no necesitaba ser perfecto; bastaba con sentirse libre, acompañada y feliz.'},
  {title:'La nueva del salón',category:'Escuela',icon:'✎',text:'Una alumna nueva llamada Elisa llegó al salón y pasó la mañana sin hablar con nadie. Serena reconoció esa mirada de quien desea acercarse, pero no encuentra cómo. Durante el almuerzo, llevó su bandeja hasta su mesa y comenzó a contarle, entre risas, cuáles profesores olvidaban poner tarea. Elisa terminó confesando que extrañaba su antigua ciudad. Al acabar el día ya caminaban juntas hacia la salida. Serena entendió que una amistad puede empezar con algo muy pequeño: dejar un lugar libre en la mesa y hacer una pregunta sincera.'},
  {title:'El regalo de mamá',category:'Familia',icon:'❀',text:'Serena quería comprarle a su madre un regalo elegante, pero sus ahorros apenas alcanzaban para una cinta. Después de pensarlo, abrió una caja de fotografías y eligió diez momentos felices de la familia. Los pegó en un cuaderno, añadió dibujos y escribió por qué cada recuerdo era especial. El día de su cumpleaños, su madre leyó todas las páginas lentamente y acabó abrazándola con los ojos húmedos. Serena comprendió entonces que el valor de un regalo no vive en su precio, sino en el tiempo, la atención y el cariño que lleva dentro.'},
  {title:'El cachorro del parque',category:'Mascotas',icon:'♧',text:'Mientras corría por el parque, Serena encontró un cachorro solo junto a la fuente. Llevaba collar, pero ninguna placa. Le dio agua y, con ayuda de sus amigas, preguntó a cada persona que pasaba. El cachorro movía la cola como si todo fuera una aventura. Una hora después, un niño apareció llorando y gritó su nombre: Copito. El reencuentro emocionó a todos. Serena volvió a casa con el uniforme lleno de huellas, pero muy contenta. Ayudar a alguien, pensó, también puede ser una forma sencilla de transformar una tarde común.'},
  {title:'Una promesa al atardecer',category:'Amor',icon:'♡',text:'Darien debía viajar durante las vacaciones y Serena fingió que la noticia no le importaba. Sin embargo, al despedirse en la estación, las palabras se le quedaron atrapadas. Él le entregó una pequeña libreta para que anotara todo lo que quisiera contarle a su regreso. Serena le regaló su pañuelo amarillo y prometió escribir una página cada día. Cuando el tren partió, sintió tristeza, pero también calma. Aprendió que querer a alguien no significa tenerlo siempre cerca: a veces el amor también sabe esperar, recordar y confiar en un próximo encuentro.'},
  {title:'La función de primavera',category:'Amistad',icon:'★',text:'En la función de primavera, Serena debía decir la última frase de la obra. Había ensayado durante semanas, pero al ver al público olvidó cada palabra. Desde un lado del escenario, sus amigas hicieron discretamente el gesto que habían practicado. Serena recordó la frase, levantó la voz y terminó con una reverencia. Los aplausos llenaron el teatro. Después, compartió las flores con todo el elenco porque sabía que aquel triunfo no era solo suyo. Esa noche comprendió que pedir apoyo no disminuye nuestros logros; permite que las personas que queremos brillen también con nosotros.'},
  {title:'El almuerzo fugitivo',category:'Escuela y humor',icon:'🍙',text:'Serena llegó al patio con un almuerzo tan bien ordenado que quiso mostrárselo a todas. Justo entonces, Luna saltó a la mesa atraída por una croqueta. La caja salió disparada, rodó por una banca y aterrizó frente al director. Él la abrió con mucha seriedad, tomó un brócoli y preguntó si era una entrega especial. Serena se disculpó mientras sus amigas contenían la risa. El director devolvió la caja y confesó que el brócoli era su enemigo desde primero básico. Al final, todos compartieron sus almuerzos y Luna recibió una croqueta, pero solo después de prometer —con un maullido muy poco convincente— no perseguir cajas otra vez.',questions:[{prompt:'¿Por qué Luna saltó a la mesa?',options:['Porque perseguía una mariposa','Porque le atrajo una croqueta','Porque quería saludar al director'],answer:1},{prompt:'¿Qué alimento dijo no soportar el director?',options:['El brócoli','La croqueta','El arroz'],answer:0}]},
  {title:'El hechizo del peinado',category:'Amistad y humor',icon:'✦',text:'Minako aseguró que había aprendido un peinado “rápido y elegante” en una revista. Serena aceptó ser su modelo, aunque Luna se escondió bajo la cama por precaución. Diez minutos después, el cabello de Serena tenía seis cintas, tres lápices y una cuchara que nadie recordaba haber usado. Cuando Rei llegó, contempló la obra y dijo que parecía una antena capaz de conversar con Marte. Todas estallaron en carcajadas. Desarmaron el peinado y descubrieron que la cuchara pertenecía al desayuno de Serena. Al final, eligieron dos coletas sencillas. Serena aprendió que las mejores amigas no siempre mejoran tu aspecto, pero sí consiguen que te rías de él.',questions:[{prompt:'¿Quién intentó peinar a Serena?',options:['Rei','Luna','Minako'],answer:2},{prompt:'¿Qué objeto inesperado apareció en el peinado?',options:['Una cuchara','Un paraguas','Un zapato'],answer:0}]},
  {title:'La serenata equivocada',category:'Romance y humor',icon:'♫',text:'Darien quiso sorprender a Serena con una serenata bajo su ventana. Practicó una canción, llevó una guitarra prestada y esperó hasta que se encendió una luz. Cantó con tanto entusiasmo que hasta los perros del barrio hicieron coro. Entonces se abrió la ventana… pero apareció el señor Gómez, el vecino, con gorro de dormir y cepillo de dientes. Darien se había equivocado de casa. Serena, que escuchó la música desde la vereda de al lado, llegó riéndose y aplaudió el final. El señor Gómez pidió otra canción, pero más corta. Darien se puso rojo; Serena le tomó la mano y dijo que era la serenata más desastrosa y encantadora que había recibido.',questions:[{prompt:'¿Por qué apareció el señor Gómez?',options:['Darien cantó bajo la casa equivocada','Quería prestar una guitarra','Era profesor de música'],answer:0},{prompt:'¿Cómo reaccionó Serena ante la serenata?',options:['Se enojó y se fue','Se rio y aplaudió','No alcanzó a escucharla'],answer:1}]},
  {title:'Luna va al veterinario',category:'Mascotas y humor',icon:'♧',text:'Luna escuchó la palabra “veterinario” y se transformó, sin magia alguna, en una estatua bajo el sofá. Serena intentó atraerla con comida, un ovillo y hasta una solemne promesa de no cantar en la ducha. Nada funcionó. Ami sugirió colocar la caja de transporte junto a la ventana. Luna salió para investigar y, con un tropiezo digno de una heroína, cayó directamente dentro. En la consulta se portó tan tranquila que la veterinaria la felicitó. De regreso, Luna caminó con aire victorioso, como si todo hubiese sido idea suya. Serena no discutió: sabía que una gata orgullosa siempre tiene la última palabra… o el último maullido.',questions:[{prompt:'¿Dónde se escondió Luna al oír “veterinario”?',options:['Bajo el sofá','Dentro del armario','Detrás de una cortina'],answer:0},{prompt:'¿Cómo entró finalmente en la caja?',options:['Serena la empujó','Cayó dentro al investigar','La veterinaria la llamó'],answer:1}]},
  {title:'Panqueques con superpoderes',category:'Familia y humor',icon:'☾',text:'Serena decidió preparar panqueques para demostrar que podía cocinar sin ayuda. El primero quedó pegado al techo. El segundo parecía un mapa de un país desconocido. El tercero salió tan redondo que su hermano preguntó si tenía superpoderes. Serena, confiada, intentó voltearlo en el aire; el panqueque aterrizó sobre la cabeza de su padre justo cuando entraba a la cocina. Hubo un segundo de silencio y luego él declaró que era el sombrero más delicioso del mundo. Entre risas, la familia terminó cocinando junta. El último panqueque no fue perfecto, pero llegó al plato, lo cual todos consideraron una gran victoria culinaria.',questions:[{prompt:'¿Dónde quedó pegado el primer panqueque?',options:['En la ventana','En el techo','En la puerta'],answer:1},{prompt:'¿Quién recibió un panqueque en la cabeza?',options:['El padre de Serena','El hermano de Serena','Luna'],answer:0}]},
  {title:'El examen de Luna',category:'Escuela y humor',icon:'✎',text:'Serena estudiaba para una prueba cuando se quedó dormida sobre el cuaderno. Luna decidió ayudar y caminó por el teclado de la computadora. A la mañana siguiente, Serena encontró una guía de estudio que decía: “Historia universal: miau, miau, tecla siete”. Pensó que era una técnica secreta de Ami y la memorizó por si acaso. Durante el examen apareció una pregunta sobre Egipto. Serena recordó que los gatos eran importantes allí y sonrió al pensar que Luna, por accidente, sí le había dado una pista. Respondió correctamente. Cuando contó la historia, Ami aclaró entre risas que “tecla siete” todavía no era un método científico.',questions:[{prompt:'¿Qué hizo Luna mientras Serena dormía?',options:['Ordenó los libros','Caminó sobre el teclado','Respondió el examen'],answer:1},{prompt:'¿Qué recuerdo ayudó a Serena con Egipto?',options:['Que los gatos eran importantes','Que Ami viajó allí','Que la tecla siete era egipcia'],answer:0}]},
  {title:'La foto familiar perfecta',category:'Familia y humor',icon:'❀',text:'La madre de Serena quería una foto familiar perfecta. Todos se peinaron, se acomodaron y miraron a la cámara. En el primer intento, el padre estornudó. En el segundo, el hermano cerró los ojos. En el tercero, Luna cruzó frente al lente mostrando solamente su enorme cola. Después de quince intentos, ya nadie sonreía de verdad. Serena puso el temporizador una última vez, pero tropezó al correr y cayó sobre el sofá. Todos comenzaron a reír, incluso Luna pareció sonreír. Esa fue la fotografía elegida: despeinada, movida y feliz. La madre de Serena dijo que era perfecta porque, por fin, se parecía a su familia.',questions:[{prompt:'¿Qué mostró Luna en el tercer intento?',options:['Su enorme cola','Una cinta roja','Un juguete'],answer:0},{prompt:'¿Por qué eligieron la última foto?',options:['Todos aparecían muy serios','Era la única foto sin Luna','Mostraba a la familia riendo de verdad'],answer:2}]},
  {title:'El baile de los zapatos rebeldes',category:'Romance y humor',icon:'♬',text:'Para el baile, Serena estrenó unos zapatos tan brillantes como incómodos. En la primera canción pisó a Darien. En la segunda volvió a pisarlo. En la tercera, él preguntó si aquello era un nuevo paso de combate. Serena decidió quitarse los zapatos y esconderlos bajo una mesa, pero Luna apareció persiguiendo los cordones y arrastró uno hasta el centro de la pista. Todos miraron el zapato viajero. Serena hizo una reverencia y anunció: “¡Mi pareja de baile!”. Darien se rio y ambos siguieron bailando descalzos. Serena descubrió que una noche puede ser elegante incluso cuando tus zapatos intentan escapar.',questions:[{prompt:'¿Por qué Serena se quitó los zapatos?',options:['Eran incómodos y pisaba a Darien','No combinaban con su vestido','Luna se los pidió'],answer:0},{prompt:'¿Quién arrastró un zapato a la pista?',options:['Darien','Minako','Luna'],answer:2}]},
  {title:'El héroe del paraguas',category:'Amor y humor',icon:'♡',text:'Comenzó a llover al salir de clases y Darien apareció con un paraguas, decidido a ser muy galante. Lo abrió con un gesto heroico, pero una ráfaga lo dio vuelta como un tazón. Serena intentó ayudar; otra ráfaga los hizo girar y terminaron refugiados bajo el pequeño techo de una tienda. Darien miró el paraguas torcido y aseguró que era un modelo especial para recoger lluvia. Serena soltó una carcajada. El dueño de la tienda les prestó uno enorme, decorado con patitos amarillos. Caminaron juntos y secos, aunque nada misteriosos. Cada vez que se miraban bajo los patitos, volvían a reír.',questions:[{prompt:'¿Qué le ocurrió al paraguas de Darien?',options:['Se perdió en un autobús','El viento lo dio vuelta','Luna le hizo un agujero'],answer:1},{prompt:'¿Cómo era el paraguas que les prestaron?',options:['Tenía patitos amarillos','Era negro y pequeño','Parecía un tazón'],answer:0}]},
  {title:'La obra del dragón dormido',category:'Amistad y humor',icon:'★',text:'En la obra escolar, Serena interpretaba a una princesa y Mauricio era el temible dragón. Todo iba bien hasta que Mauricio, escondido dentro del disfraz, se quedó dormido esperando su escena. Serena recitó: “¡Oh, feroz criatura!”, pero el dragón respondió con un ronquido. El público creyó que era parte de la comedia y comenzó a reír. Rei, desde bambalinas, hizo sonar dos tapas de ollas. Mauricio despertó sobresaltado, dio tres vueltas y declaró: “¡Nadie interrumpe la siesta del dragón!”. Los aplausos fueron enormes. Después, el grupo decidió conservar la escena. A veces, el mejor momento de una función es el que nadie ensayó.',questions:[{prompt:'¿Por qué el dragón no respondió al principio?',options:['Había olvidado el texto','Se había quedado dormido','No encontraba el escenario'],answer:1},{prompt:'¿Cómo despertó Rei a Mauricio?',options:['Con dos tapas de ollas','Con una canción','Con un balde de agua'],answer:0}]}
];

const Moon=()=> <svg viewBox="0 0 64 64" aria-hidden="true"><path d="M45 7a25 25 0 1 0 11 40A27 27 0 0 1 45 7Z"/><path className="star" d="m16 12 2 5 5 2-5 2-2 5-2-5-5-2 5-2 2-5Z"/></svg>;

export default function App(){
 const [started,setStarted]=useState(false),[current,setCurrent]=useState(0),[textSize,setTextSize]=useState<'small'|'medium'|'large'>(()=>{
  const saved=localStorage.getItem('serena-text-size');
  return saved==='small'||saved==='large'?saved:'medium';
 }),[read,setRead]=useState<number[]>(()=>{
  try {
   const saved=JSON.parse(localStorage.getItem('serena-read')||'[]');
   return Array.isArray(saved)?saved:[];
  } catch {
   return [];
  }
 }),[answers,setAnswers]=useState<Record<string,number>>({});
 useEffect(()=>localStorage.setItem('serena-read',JSON.stringify(read)),[read]);
 useEffect(()=>localStorage.setItem('serena-text-size',textSize),[textSize]);
 const story=stories[current], done=read.includes(current), pct=Math.round(read.length/stories.length*100);
 const mark=()=>setRead(r=>r.includes(current)?r:[...r,current]);
 const answerQuestion=(question:number,option:number)=>setAnswers(previous=>({...previous,[`${current}-${question}`]:option}));
 const nextTextSize=textSize==='small'?'medium':textSize==='medium'?'large':'small';
 const textSizeName={small:'pequeño',medium:'mediano',large:'grande'}[textSize];
 if(!started)return <div className="landing"><div className="spark s1">✦</div><div className="spark s2">✧</div><main className="welcome"><section className="intro"><div className="brand"><span className="moon"><Moon/></span><span>Club de lectura lunar</span></div><p className="subject">LENGUAJE · COMPRENSIÓN LECTORA</p><h1>Lecturas de<br/><em>Sailor Moon</em></h1><p className="lead">Acompaña a Serena en 20 pequeñas historias sobre la amistad, el amor y la familia. Los 10 cuentos nuevos llegan con mucho humor y un desafío de comprensión.</p><button className="start" onClick={()=>setStarted(true)}>Comenzar a leer <span>→</span></button><div className="resume"><div className="mini-progress"><i style={{width:`${pct}%`}}/></div><b>{read.length} de {stories.length}</b><span> cuentos leídos</span></div></section><section className="portrait"><div className="orb"><div className="orbit">✦</div><img src={serena} alt="Serena, Sailor Moon"/></div><span className="badge"><b>{stories.length}</b> cuentos<br/>mágicos</span></section></main><footer>☾ &nbsp; Lee a tu ritmo, ríe sin límites &nbsp; ✦</footer></div>;
 return <div className="reader"><header><button className="logo" onClick={()=>setStarted(false)}><span className="moon"><Moon/></span><b>Lecturas de<br/><em>Sailor Moon</em></b></button><div className="top-progress"><div><span>Tu progreso lunar</span><b>{read.length} / {stories.length} cuentos</b></div><div className="track"><i style={{width:`${pct}%`}}/><span style={{left:`calc(${pct}% - 12px)`}}>☾</span></div></div></header><main className="reading-layout"><aside><p className="aside-label">COLECCIÓN DE CUENTOS</p><nav>{stories.map((s,i)=><button key={s.title} className={`${i===current?'active':''} ${read.includes(i)?'finished':''}`} onClick={()=>setCurrent(i)}><span>{read.includes(i)?'✓':i+1}</span><div><b>{s.title}</b><small>{s.category}</small></div></button>)}</nav></aside><article><div className="paper-stars">✦　·　☾</div><button className="text-size-button" onClick={()=>setTextSize(nextTextSize)} aria-label={`Tamaño del texto: ${textSizeName}. Cambiar tamaño`} title={`Texto ${textSizeName}`}><span>A</span>A</button><div className="story-meta"><span>{story.icon} {story.category}</span><small>CUENTO {current+1} DE {stories.length}</small></div><h1>{story.title}</h1><div className="divider"><i/><span>☾</span><i/></div><p className={`story-text text-${textSize}`}>{story.text}</p>{story.questions&&<section className="quiz"><div className="quiz-heading"><span>☾</span><div><small>DESAFÍO LUNAR</small><h2>Comprueba tu lectura</h2></div></div>{story.questions.map((question,questionIndex)=>{const selected=answers[`${current}-${questionIndex}`];return <fieldset key={question.prompt}><legend><b>{questionIndex+1}</b>{question.prompt}</legend><div className="quiz-options">{question.options.map((option,optionIndex)=>{const answered=selected!==undefined;const status=answered?(optionIndex===question.answer?'correct':optionIndex===selected?'incorrect':''):'';return <button type="button" className={status} aria-pressed={selected===optionIndex} onClick={()=>answerQuestion(questionIndex,optionIndex)} key={option}><span>{String.fromCharCode(65+optionIndex)}</span>{option}</button>})}</div>{selected!==undefined&&<p className={selected===question.answer?'feedback correct':'feedback incorrect'} role="status">{selected===question.answer?'✓ ¡Respuesta correcta!':'✦ Inténtalo otra vez y busca la pista en el cuento.'}</p>}</fieldset>})}</section>}<div className="reflection"><span>✦</span><div><b>Un momento para pensar</b><p>¿Qué habrías hecho tú en el lugar de Serena?</p></div></div><div className="actions"><button className="prev" disabled={current===0} onClick={()=>setCurrent(c=>c-1)}>← <span>Anterior</span></button><button className={done?'read done':'read'} onClick={mark}>{done?'✓ Cuento leído':'Marcar como leído'} </button><button className="next" disabled={current===stories.length-1} onClick={()=>{mark();setCurrent(c=>Math.min(stories.length-1,c+1))}}><span>Siguiente</span> →</button></div></article></main></div>;
}
