import {useMemo,useState} from 'react';import type {Exercise,Level,WorldId} from './types/exercise';import {worlds} from './data/worlds';import {makeExercise} from './utils/exerciseGenerators';import {useProgress} from './hooks/useProgress';import {useSound} from './hooks/useSound';import {Character} from './components/Character';import {GameHeader} from './components/GameHeader';import {ProgressBar} from './components/ProgressBar';import {Feedback} from './components/Feedback';import {ResultScreen} from './components/ResultScreen';import {ExerciseCard} from './games/ExerciseCard';
type Screen='menu'|'levels'|'game'|'result';
const cheers=['¡Muy bien!','¡Excelente!','¡Lo lograste!','¡Qué genial!'];
export default function App(){const {stats,finish}=useProgress(),sound=useSound();const [screen,setScreen]=useState<Screen>('menu'),[world,setWorld]=useState<WorldId>(),[level,setLevel]=useState<Level>(1),[challenge,setChallenge]=useState(false),[index,setIndex]=useState(0),[correct,setCorrect]=useState(0),[streak,setStreak]=useState(0),[best,setBest]=useState(0),[errors,setErrors]=useState(0),[selected,setSelected]=useState<string>(),[locked,setLocked]=useState(false),[feedback,setFeedback]=useState('');const total=challenge?15:10;
 const exercise=useMemo<Exercise|null>(()=>screen==='game'?makeExercise(challenge?worlds[Math.floor(Math.random()*worlds.length)].id:world!,challenge?3:level):null,[screen,index,world,level,challenge]);
 const home=()=>{setScreen('menu');setChallenge(false)};const start=(l:Level,isChallenge=false)=>{setLevel(l);setChallenge(isChallenge);setIndex(0);setCorrect(0);setStreak(0);setBest(0);setErrors(0);setSelected(undefined);setLocked(false);setFeedback('');setScreen('game')};
 const answer=(value:string)=>{if(locked||!exercise)return;if(value===exercise.answer){const ns=streak+1;setCorrect(c=>c+1);setStreak(ns);setBest(b=>Math.max(b,ns));setLocked(true);setSelected(undefined);setFeedback(cheers[Math.floor(Math.random()*cheers.length)]);sound.play('good')}else{const ne=errors+1;setErrors(ne);setStreak(0);setSelected(value);setFeedback(ne>=2?exercise.explanation:`Casi, intenta otra vez. ${exercise.hint}`);sound.play('try')}};
 const next=()=>{if(index+1>=total){finish(world,correct,best,challenge);sound.play('done');setScreen('result')}else{setIndex(i=>i+1);setErrors(0);setSelected(undefined);setLocked(false);setFeedback('')}};
 if(screen==='result')return <div className="app-shell"><GameHeader stars={stats.stars+correct} correct={correct} streak={streak} sound={sound.enabled} onSound={()=>sound.setEnabled(!sound.enabled)} onHome={home}/><ResultScreen total={total} correct={correct} best={best} onAgain={()=>start(level,challenge)} onWorlds={home}/></div>;
 return <div className="app-shell"><GameHeader stars={stats.stars+(screen==='game'?correct:0)} correct={correct} streak={streak} sound={sound.enabled} onSound={()=>sound.setEnabled(!sound.enabled)} onHome={home}/>{screen==='menu'&&<main className="menu"><div className="hero"><div><span className="eyebrow">EVALUACIÓN DEL 12 DE AGOSTO</span><h1>¡Aventura<br/><em>Matemática!</em></h1><p>Explora, juega y conquista las matemáticas.</p></div><Character/></div><h2>Elige tu mundo</h2><div className="world-grid">{worlds.map(w=><button className="world-card" style={{'--accent':w.color} as React.CSSProperties} key={w.id} onClick={()=>{setWorld(w.id);setScreen('levels')}}><span className="world-emoji">{w.emoji}</span><span><b>{w.title}</b><small>{w.subtitle}</small></span>{stats.completed.includes(w.id)&&<i>✓</i>}</button>)}</div><button className="challenge" onClick={()=>start(3,true)}><span>🎯</span><b>Desafío final</b><small>15 preguntas de todos los mundos · Récord: {stats.bestChallenge}</small></button></main>}
 {screen==='levels'&&<main className="levels card"><Character message="¿Cuánto quieres explorar?"/><h1>Elige un nivel</h1><p>{worlds.find(w=>w.id===world)?.title}</p>{([1,2,3] as Level[]).map(l=><button key={l} onClick={()=>start(l)}><b>{'⭐'.repeat(l)} {['Fácil','Medio','Difícil'][l-1]}</b><span>{l===1?'Primeros pasos':l===2?'Un poco más lejos':'¡Gran aventura!'}</span></button>)}</main>}
 {screen==='game'&&exercise&&<main className="play"><ProgressBar current={index} total={total}/><Character mood={locked?'happy':errors?'help':'hello'} message={feedback||(challenge?'¡Sorpresa de todos los mundos!':'¡Tú puedes!')}/><ExerciseCard exercise={exercise} selected={selected} onAnswer={answer} disabled={locked}/>{feedback&&<Feedback kind={locked?'good':'help'} text={feedback}/>} {locked&&<button className="primary next" onClick={next}>{index+1===total?'Ver mi premio':'Siguiente →'}</button>}</main>}</div>}
