import {useEffect, useState} from 'react';
import serena from './file_000000003f60820eb8adacc5bed5ae6c.png';

type Story={title:string; category:string; icon:string; text:string};

const stories:Story[]=[
  {title:'La carta bajo la lluvia',category:'Amor',icon:'♡',text:'Serena encontró una carta doblada bajo el banco del patio justo cuando empezó a llover. No tenía nombre, solo una frase: “Tu risa ilumina los días difíciles”. Durante toda la clase pensó que quizá era para ella. Al salir, vio a Mateo buscando algo entre los charcos. Serena le devolvió la carta y él, muy colorado, confesó que aún no se atrevía a entregársela. Caminaron juntos bajo el paraguas. No hicieron grandes promesas; compartieron una sonrisa tímida y la certeza de que algo bonito acababa de comenzar.'},
  {title:'El examen imposible',category:'Escuela',icon:'✦',text:'El lunes, Serena descubrió que el examen de historia era mucho más difícil de lo esperado. Por un instante quiso rendirse, pero recordó las tardes estudiando con Ami. Respiró profundo y respondió primero las preguntas que conocía. Después regresó a las complicadas y encontró pistas entre sus propios apuntes mentales. Al terminar, no sabía si obtendría la mejor nota, aunque se sentía orgullosa. Esa tarde comprendió que ser valiente no significa saberlo todo, sino confiar en el esfuerzo realizado y seguir adelante cuando aparecen las dudas.'},
  {title:'Domingo de panqueques',category:'Familia',icon:'☾',text:'El domingo, Serena despertó con olor a panqueques y encontró a su hermano intentando preparar el desayuno. La cocina parecía un campo de batalla: harina en el suelo, leche sobre la mesa y una montaña de platos. En vez de burlarse, se puso un delantal y decidió ayudarlo. Su madre llegó justo cuando ambos servían el panqueque más torcido del mundo. Los tres rieron tanto que casi olvidaron comer. Serena guardó aquel momento en su corazón, porque entendió que los recuerdos perfectos suelen nacer de planes completamente imperfectos.'},
  {title:'Luna no vuelve a casa',category:'Mascotas',icon:'♧',text:'Luna no regresó a la hora de cenar y Serena recorrió el vecindario llamándola con el corazón acelerado. Preguntó en la tienda, miró bajo los autos y pegó pequeños avisos en los postes. Cuando ya anochecía, escuchó un maullido cerca de la biblioteca. Luna estaba en una rama, asustada pero ilesa. Serena pidió ayuda para bajarla y la abrazó con fuerza. De regreso en casa, prometió revisar siempre la ventana. Aquella noche, Luna durmió a sus pies y Serena agradeció en silencio tener nuevamente cerca a su pequeña compañera.'},
  {title:'Un baile inesperado',category:'Romance',icon:'♬',text:'Serena pensaba quedarse en casa la noche del baile escolar porque no tenía pareja. Minako apareció con un vestido prestado y una idea sencilla: irían juntas a divertirse. En el gimnasio, las luces parecían estrellas y la música borró pronto la vergüenza. Cerca del final, Darien le ofreció la mano y preguntó si quería bailar. Serena tropezó en el primer paso, pero él sonrió y continuaron. Descubrió que el momento romántico que había imaginado no necesitaba ser perfecto; bastaba con sentirse libre, acompañada y feliz.'},
  {title:'La nueva del salón',category:'Escuela',icon:'✎',text:'Una alumna nueva llamada Elisa llegó al salón y pasó la mañana sin hablar con nadie. Serena reconoció esa mirada de quien desea acercarse, pero no encuentra cómo. Durante el almuerzo, llevó su bandeja hasta su mesa y comenzó a contarle, entre risas, cuáles profesores olvidaban poner tarea. Elisa terminó confesando que extrañaba su antigua ciudad. Al acabar el día ya caminaban juntas hacia la salida. Serena entendió que una amistad puede empezar con algo muy pequeño: dejar un lugar libre en la mesa y hacer una pregunta sincera.'},
  {title:'El regalo de mamá',category:'Familia',icon:'❀',text:'Serena quería comprarle a su madre un regalo elegante, pero sus ahorros apenas alcanzaban para una cinta. Después de pensarlo, abrió una caja de fotografías y eligió diez momentos felices de la familia. Los pegó en un cuaderno, añadió dibujos y escribió por qué cada recuerdo era especial. El día de su cumpleaños, su madre leyó todas las páginas lentamente y acabó abrazándola con los ojos húmedos. Serena comprendió entonces que el valor de un regalo no vive en su precio, sino en el tiempo, la atención y el cariño que lleva dentro.'},
  {title:'El cachorro del parque',category:'Mascotas',icon:'♧',text:'Mientras corría por el parque, Serena encontró un cachorro solo junto a la fuente. Llevaba collar, pero ninguna placa. Le dio agua y, con ayuda de sus amigas, preguntó a cada persona que pasaba. El cachorro movía la cola como si todo fuera una aventura. Una hora después, un niño apareció llorando y gritó su nombre: Copito. El reencuentro emocionó a todos. Serena volvió a casa con el uniforme lleno de huellas, pero muy contenta. Ayudar a alguien, pensó, también puede ser una forma sencilla de transformar una tarde común.'},
  {title:'Una promesa al atardecer',category:'Amor',icon:'♡',text:'Darien debía viajar durante las vacaciones y Serena fingió que la noticia no le importaba. Sin embargo, al despedirse en la estación, las palabras se le quedaron atrapadas. Él le entregó una pequeña libreta para que anotara todo lo que quisiera contarle a su regreso. Serena le regaló su pañuelo amarillo y prometió escribir una página cada día. Cuando el tren partió, sintió tristeza, pero también calma. Aprendió que querer a alguien no significa tenerlo siempre cerca: a veces el amor también sabe esperar, recordar y confiar en un próximo encuentro.'},
  {title:'La función de primavera',category:'Amistad',icon:'★',text:'En la función de primavera, Serena debía decir la última frase de la obra. Había ensayado durante semanas, pero al ver al público olvidó cada palabra. Desde un lado del escenario, sus amigas hicieron discretamente el gesto que habían practicado. Serena recordó la frase, levantó la voz y terminó con una reverencia. Los aplausos llenaron el teatro. Después, compartió las flores con todo el elenco porque sabía que aquel triunfo no era solo suyo. Esa noche comprendió que pedir apoyo no disminuye nuestros logros; permite que las personas que queremos brillen también con nosotros.'}
];

const Moon=()=> <svg viewBox="0 0 64 64" aria-hidden="true"><path d="M45 7a25 25 0 1 0 11 40A27 27 0 0 1 45 7Z"/><path className="star" d="m16 12 2 5 5 2-5 2-2 5-2-5-5-2 5-2 2-5Z"/></svg>;

export default function App(){
 const [started,setStarted]=useState(false),[current,setCurrent]=useState(0),[read,setRead]=useState<number[]>(()=>JSON.parse(localStorage.getItem('serena-read')||'[]'));
 useEffect(()=>localStorage.setItem('serena-read',JSON.stringify(read)),[read]);
 const story=stories[current], done=read.includes(current), pct=Math.round(read.length/stories.length*100);
 const mark=()=>setRead(r=>r.includes(current)?r:[...r,current]);
 if(!started)return <div className="landing"><div className="spark s1">✦</div><div className="spark s2">✧</div><main className="welcome"><section className="intro"><div className="brand"><span className="moon"><Moon/></span><span>Club de lectura lunar</span></div><p className="subject">LENGUAJE · COMPRENSIÓN LECTORA</p><h1>Lecturas de<br/><em>Sailor Moon</em></h1><p className="lead">Acompaña a Serena en 10 pequeñas historias sobre la amistad, el amor y esos momentos que hacen inolvidable la adolescencia.</p><button className="start" onClick={()=>setStarted(true)}>Comenzar a leer <span>→</span></button><div className="resume"><div className="mini-progress"><i style={{width:`${pct}%`}}/></div><b>{read.length} de 10</b><span> cuentos leídos</span></div></section><section className="portrait"><div className="orb"><div className="orbit">✦</div><img src={serena} alt="Serena, Sailor Moon"/></div><span className="badge"><b>10</b> cuentos<br/>mágicos</span></section></main><footer>☾ &nbsp; Lee a tu ritmo, sueña sin límites &nbsp; ✦</footer></div>;
 return <div className="reader"><header><button className="logo" onClick={()=>setStarted(false)}><span className="moon"><Moon/></span><b>Lecturas de<br/><em>Sailor Moon</em></b></button><div className="top-progress"><div><span>Tu progreso lunar</span><b>{read.length} / 10 cuentos</b></div><div className="track"><i style={{width:`${pct}%`}}/><span style={{left:`calc(${pct}% - 12px)`}}>☾</span></div></div></header><main className="reading-layout"><aside><p className="aside-label">COLECCIÓN DE CUENTOS</p><nav>{stories.map((s,i)=><button key={s.title} className={`${i===current?'active':''} ${read.includes(i)?'finished':''}`} onClick={()=>setCurrent(i)}><span>{read.includes(i)?'✓':i+1}</span><div><b>{s.title}</b><small>{s.category}</small></div></button>)}</nav></aside><article><div className="paper-stars">✦　·　☾</div><div className="story-meta"><span>{story.icon} {story.category}</span><small>CUENTO {current+1} DE 10</small></div><h1>{story.title}</h1><div className="divider"><i/><span>☾</span><i/></div><p className="story-text">{story.text}</p><div className="reflection"><span>✦</span><div><b>Un momento para pensar</b><p>¿Qué habrías hecho tú en el lugar de Serena?</p></div></div><div className="actions"><button className="prev" disabled={current===0} onClick={()=>setCurrent(c=>c-1)}>← <span>Anterior</span></button><button className={done?'read done':'read'} onClick={mark}>{done?'✓ Cuento leído':'Marcar como leído'} </button><button className="next" disabled={current===9} onClick={()=>{mark();setCurrent(c=>Math.min(9,c+1))}}><span>Siguiente</span> →</button></div></article></main></div>;
}
